Remove the unsupported cluster versions in upgrade environment
open-cluster-management-io/multicloud-operators-subscription pull request #250
Opened 2022-09-14 18:33 UTC by lennysgarage

Signed-off-by: Jonathan Marcantonio <jmarcant@redhat.com>

Adds a new function, `getResourcesByLegacySubStatus` to grab the resource list deployed by the legacy subscription controller.
Compares legacy resources to new resources and removes orphaned resources that are not present in the new controller.

Addresses:
- https://github.com/stolostron/backlog/issues/25346

2022-09-14 19:15 UTC, mikeshng requested changes
Dropping a general feedback for now. 
I see a couple usage of `strings.Index` then assume the return value is the desired result.
I feel like this might not be safe enough incase of bad inputs.

Could you please add some sanity check to make sure we won't get some arrayoutofbound errors which will crashloop the pod if there is a subscription with some unexpected data? Could you also add some tests afterwards so that even with unexpected data it will not crash? Thanks!

2022-09-16 18:09 UTC, lennysgarage commented on pkg/synchronizer/kubernetes/sync_appsubstatus.go
> +					if err := sync.RemoteClient.Get(context.TODO(),
Fixed!

2022-09-16 18:09 UTC, lennysgarage commented on pkg/synchronizer/kubernetes/sync_appsubstatus.go
> +					if err := sync.RemoteClient.Status().Update(context.TODO(), appsub); err != nil {
Fixed!

2022-09-19 14:49 UTC, mikeshng commented
Nice! 

Going to let Xiangjing do the approval.

2022-09-19 14:52 UTC, xiangjingli approved these changes

2022-09-19 15:24 UTC, merged